# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/snake_game.xdc

# IP: ip/font_romv1/font_romv1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==font_romv1 || ORIG_REF_NAME==font_romv1} -quiet] -quiet
