# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/microblaze.xdc

# Block Designs: bd/MicroBlazeDemo1/MicroBlazeDemo1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlazeDemo1 || ORIG_REF_NAME==MicroBlazeDemo1} -quiet] -quiet

# IP: bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_microblaze_0_0/MicroBlazeDemo1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlazeDemo1_microblaze_0_0 || ORIG_REF_NAME==MicroBlazeDemo1_microblaze_0_0} -quiet] -quiet

# IP: bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_axi_uartlite_0_0/MicroBlazeDemo1_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlazeDemo1_axi_uartlite_0_0 || ORIG_REF_NAME==MicroBlazeDemo1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_dlmb_v10_0/MicroBlazeDemo1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlazeDemo1_dlmb_v10_0 || ORIG_REF_NAME==MicroBlazeDemo1_dlmb_v10_0} -quiet] -quiet

# IP: bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_ilmb_v10_0/MicroBlazeDemo1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlazeDemo1_ilmb_v10_0 || ORIG_REF_NAME==MicroBlazeDemo1_ilmb_v10_0} -quiet] -quiet

# IP: bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_dlmb_bram_if_cntlr_0/MicroBlazeDemo1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlazeDemo1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroBlazeDemo1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_ilmb_bram_if_cntlr_0/MicroBlazeDemo1_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlazeDemo1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroBlazeDemo1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_lmb_bram_0/MicroBlazeDemo1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlazeDemo1_lmb_bram_0 || ORIG_REF_NAME==MicroBlazeDemo1_lmb_bram_0} -quiet] -quiet

# IP: bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_mdm_1_0/MicroBlazeDemo1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlazeDemo1_mdm_1_0 || ORIG_REF_NAME==MicroBlazeDemo1_mdm_1_0} -quiet] -quiet

# IP: bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_clk_wiz_1_0/MicroBlazeDemo1_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlazeDemo1_clk_wiz_1_0 || ORIG_REF_NAME==MicroBlazeDemo1_clk_wiz_1_0} -quiet] -quiet

# IP: bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_rst_clk_wiz_1_100M_0/MicroBlazeDemo1_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlazeDemo1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MicroBlazeDemo1_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_xbar_0/MicroBlazeDemo1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlazeDemo1_xbar_0 || ORIG_REF_NAME==MicroBlazeDemo1_xbar_0} -quiet] -quiet

# IP: bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_microblaze_0_axi_periph_0/MicroBlazeDemo1_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlazeDemo1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MicroBlazeDemo1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_my_pwm_ip_0_0/MicroBlazeDemo1_my_pwm_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlazeDemo1_my_pwm_ip_0_0 || ORIG_REF_NAME==MicroBlazeDemo1_my_pwm_ip_0_0} -quiet] -quiet

# XDC: bd/MicroBlazeDemo1/MicroBlazeDemo1_ooc.xdc
