# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/FPGA/digital_system_design/_my_snake_game_/_my_snake_game_.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_my_snake_game_ip_0_0/MicroBlazeDemo1_my_snake_game_ip_0_0.xci
# IP: The module: 'MicroBlazeDemo1_my_snake_game_ip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/FPGA/digital_system_design/_my_snake_game_/_my_snake_game_.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_my_snake_game_ip_0_0/hdl/ip/font_romv1/font_romv1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==font_romv1 || ORIG_REF_NAME==font_romv1} -quiet] -quiet

# XDC: e:/FPGA/digital_system_design/_my_snake_game_/_my_snake_game_.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_my_snake_game_ip_0_0/hdl/ip/font_romv1/font_romv1_ooc.xdc

# IP: E:/FPGA/digital_system_design/_my_snake_game_/_my_snake_game_.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_my_snake_game_ip_0_0/MicroBlazeDemo1_my_snake_game_ip_0_0.xci
# IP: The module: 'MicroBlazeDemo1_my_snake_game_ip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/FPGA/digital_system_design/_my_snake_game_/_my_snake_game_.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_my_snake_game_ip_0_0/hdl/ip/font_romv1/font_romv1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==font_romv1 || ORIG_REF_NAME==font_romv1} -quiet] -quiet

# XDC: e:/FPGA/digital_system_design/_my_snake_game_/_my_snake_game_.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_my_snake_game_ip_0_0/hdl/ip/font_romv1/font_romv1_ooc.xdc
