# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 8
set_param synth.incrementalSynthesisCache E:/FPGA/digital_system_design/MicroBlaze/.Xil/Vivado-4752-DESKTOP-37A9H0N/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.cache/wt [current_project]
set_property parent.project_path E:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/hdl/MicroBlazeDemo1_wrapper.v
add_files E:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/MicroBlazeDemo1.bd
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_microblaze_0_0/MicroBlazeDemo1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_microblaze_0_0/MicroBlazeDemo1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_microblaze_0_0/MicroBlazeDemo1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_axi_gpio_0_0/MicroBlazeDemo1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_axi_gpio_0_0/MicroBlazeDemo1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_axi_gpio_0_0/MicroBlazeDemo1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_axi_uartlite_0_0/MicroBlazeDemo1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_axi_uartlite_0_0/MicroBlazeDemo1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_axi_uartlite_0_0/MicroBlazeDemo1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_dlmb_v10_0/MicroBlazeDemo1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_dlmb_v10_0/MicroBlazeDemo1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_ilmb_v10_0/MicroBlazeDemo1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_ilmb_v10_0/MicroBlazeDemo1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_dlmb_bram_if_cntlr_0/MicroBlazeDemo1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_ilmb_bram_if_cntlr_0/MicroBlazeDemo1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_lmb_bram_0/MicroBlazeDemo1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_mdm_1_0/MicroBlazeDemo1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_mdm_1_0/MicroBlazeDemo1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_clk_wiz_1_0/MicroBlazeDemo1_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_clk_wiz_1_0/MicroBlazeDemo1_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_clk_wiz_1_0/MicroBlazeDemo1_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_rst_clk_wiz_1_100M_0/MicroBlazeDemo1_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_rst_clk_wiz_1_100M_0/MicroBlazeDemo1_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_rst_clk_wiz_1_100M_0/MicroBlazeDemo1_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_xbar_0/MicroBlazeDemo1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlazeDemo1/MicroBlazeDemo1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/constrs_1/new/microblaze.xdc
set_property used_in_implementation false [get_files E:/FPGA/digital_system_design/MicroBlaze/MicroBlaze.srcs/constrs_1/new/microblaze.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MicroBlazeDemo1_wrapper -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MicroBlazeDemo1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MicroBlazeDemo1_wrapper_utilization_synth.rpt -pb MicroBlazeDemo1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
