# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Mr.LJS/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-13216-DESKTOP-37A9H0N/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/A_my_project/FPGA/zhuanyeke/alarm_clock/alarm_clock.cache/wt [current_project]
set_property parent.project_path D:/A_my_project/FPGA/zhuanyeke/alarm_clock/alarm_clock.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/A_my_project/FPGA/zhuanyeke/alarm_clock/alarm_clock.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/A_my_project/FPGA/zhuanyeke/alarm_clock/alarm_clock.srcs/sources_1/new/alarm_controller.v
  D:/A_my_project/FPGA/zhuanyeke/alarm_clock/alarm_clock.srcs/sources_1/new/alarm_counter.v
  D:/A_my_project/FPGA/zhuanyeke/alarm_clock/alarm_clock.srcs/sources_1/new/alarm_reg.v
  D:/A_my_project/FPGA/zhuanyeke/alarm_clock/alarm_clock.srcs/sources_1/new/display_driver.v
  D:/A_my_project/FPGA/zhuanyeke/alarm_clock/alarm_clock.srcs/sources_1/new/fq_divider.v
  D:/A_my_project/FPGA/zhuanyeke/alarm_clock/alarm_clock.srcs/sources_1/new/kd_encoder.v
  D:/A_my_project/FPGA/zhuanyeke/alarm_clock/alarm_clock.srcs/sources_1/new/seg_show.v
  D:/A_my_project/FPGA/zhuanyeke/alarm_clock/alarm_clock.srcs/sources_1/new/alarm_clock_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/A_my_project/FPGA/zhuanyeke/alarm_clock/alarm_clock.srcs/constrs_2/new/key_seg.xdc
set_property used_in_implementation false [get_files D:/A_my_project/FPGA/zhuanyeke/alarm_clock/alarm_clock.srcs/constrs_2/new/key_seg.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top alarm_clock_top -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef alarm_clock_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file alarm_clock_top_utilization_synth.rpt -pb alarm_clock_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
