# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/FPGA/digital_system_design/MicroBlaze_int/MicroBlaze_intr/MicroBlaze_intr.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_xbar_0/MicroBlazeDemo1_xbar_0.xci
# IP: The module: 'MicroBlazeDemo1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/digital_system_design/MicroBlaze_int/MicroBlaze_intr/MicroBlaze_intr.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_xbar_0/MicroBlazeDemo1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeDemo1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/FPGA/digital_system_design/MicroBlaze_int/MicroBlaze_intr/MicroBlaze_intr.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_xbar_0/MicroBlazeDemo1_xbar_0.xci
# IP: The module: 'MicroBlazeDemo1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/digital_system_design/MicroBlaze_int/MicroBlaze_intr/MicroBlaze_intr.srcs/sources_1/bd/MicroBlazeDemo1/ip/MicroBlazeDemo1_xbar_0/MicroBlazeDemo1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeDemo1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
